### ISSUE TITLE
Problems with kubernetes deployments

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/orchestrator#416]
I'm testing the following template:
````
topology_template:

  node_templates:

    helm:
      type: tosca.nodes.indigo.Kubernetes.HelmChart
      properties:
        repository: https://charts.bitnami.com/bitnami
        name: mysql
        version: 8.2.3
        values: 
          auth:
            rootPassword: hjhyuy8gf
          primary:
            persistence:
              enabled: false
            service:
              type: NodePort
          secondary:
            persistence:
              enabled: false
            service:
              type: NodePort
  outputs:
    endpoint:
      value:  { concat: [  { get_attribute : [ helm, worker_nodes_ips, 0 ] }, ':', { get_attribute : [ helm, service_ports, mysql, mysql, target ] } ] }
````
and I see two issues:
1. the chart cannot be installed successfully as the parameters *.persistence.enabled are passed as string instead of boolean
2. the service port is not returned as the label "release" is not attached to the release resources and therefore the filter on this label returns an empty set.

Possible solutions:
- for point 1, define the values as string in the TOSCA and parse it as yaml:
   `````
        values: |
          auth:
            rootPassword: hjhyuy8gf
          primary:
            persistence:
              enabled: false
            service:
              type: NodePort
          secondary:
            persistence:
              enabled: false
            service:
              type: NodePort
   `````

- for point 2, the best solution would be to add a custom label when deploying the HelmRelease (if this is supported) and use it to select the list of services associated to the deployed release. Please note that "release" is not a "standard" label, not even mentioned in the documentation as recommended (`app.kubernetes.io/instance` is recommended, but not mandatory) - see https://helm.sh/docs/chart_best_practices/labels/).
